# Generated by Django 5.0.1 on 2024-01-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='UserName',
            new_name='username',
        ),
    ]
